### ISSUE TITLE
Баг с кнопкой

### ISSUE THREAD

**Issue by flaber55** [spb201/visual-novel#1]
Не спадает фокус с кнопки на следующем экране, после нажатия на кнопку на предыдущем экране.

![1](https://cloud.githubusercontent.com/assets/11265306/6435822/4aa2d3c6-c0c7-11e4-98af-d7780eadea9e.png)

![2](https://cloud.githubusercontent.com/assets/11265306/6435815/2069709c-c0c7-11e4-87a3-a3669ca51f88.png)

**Comment by grdesu** [comment]
@flaber55 ты пёс
