### ISSUE TITLE
Quest viewer

### ISSUE THREAD

**Issue by flaber55** [spb201/visual-novel#10]
Если текст кнопки длинный, то выглядит это некрасиво (появляется горизонтальный скролл). Надо бы наверное добавить какой-нибудь перенос или ограничиться определенным количеством символов.

**Comment by 102** [comment]
Браузер? Разрешение экрана? ОС?
Хотя бы скриншот заливал к таким багам

**Comment by flaber55** [comment]
Windows 8
1366X768

Firefox 36.0.1
![11](https://cloud.githubusercontent.com/assets/11265306/6659377/3b6c8c84-cbae-11e4-8378-c0104baabc8d.jpg)
![22](https://cloud.githubusercontent.com/assets/11265306/6659374/3b69470e-cbae-11e4-9f2b-a4bb3b0dee0f.jpg)

IE 10
![33](https://cloud.githubusercontent.com/assets/11265306/6659375/3b6a660c-cbae-11e4-950b-e290bee8cd1c.jpg)
![44](https://cloud.githubusercontent.com/assets/11265306/6659376/3b6bb4c6-cbae-11e4-90ec-a148b097413b.jpg)
