### ISSUE TITLE
Сделать интерфейс прохождения новеллы красивым

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#109]
1) Картинку вверх (как в стандартном интерфейсе визуальных новелл). Текст возможно на фоне картинки. Референс:
![alt text](http://upload.wikimedia.org/wikipedia/commons/6/69/Wikipetan_Visual_Novel_Kor.png)
![alt text](http://3.bp.blogspot.com/-vs00GbXZpW8/UWOOfMucElI/AAAAAAAAAx8/QyQ01sEKDtg/s1600/rei+visual+novel.png)
2) У кнопок добавить марджин
3) #97

**Comment by 102** [comment]
И на весь экран картинку еще, ну

**Comment by 102** [comment]
И дефолтную картинку на квест назначать, чтобы показывать её на нодах без картинки

**Comment by leshakoss** [comment]
@102 было бы норм

**Comment by leshakoss** [comment]
@102 но естественно никто не будет делать новеллы с большими картинками

**Comment by leshakoss** [comment]
Спорные фичи: 
1) у каждого узла кроме текста может быть тайтл (см. оп пикрелейтед)
2) если у узла есть только одна связь, то у связи может отсутствовать текст, и тогда она отображается как стрелочка типа "продолжить" (см. оп пикрелейтед)
