### ISSUE TITLE
На главной у каждого квеста есть некликабельная область между описанием и автором

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#130]
![screen shot 2015-05-24 at 01 08 15](https://cloud.githubusercontent.com/assets/566319/7785433/09992ca4-01a9-11e5-86d4-a1cd5ed95c5f.png)
Здесь между фыв и by 8chnius

**Comment by 102** [comment]
Бля, я даун

**Comment by 102** [comment]
Или нет

**Comment by leshakoss** [comment]
#132
