### ISSUE TITLE
Добавить редактирование квестов

### ISSUE THREAD

**Issue by Nastuya** [spb201/visual-novel#2]
Редактирование  текста и блоков.

**Comment by 102** [comment]
Каких нахуй блоков

**Comment by Nastuya** [comment]
Ну, узлов. Как угодно назови

**Comment by 102** [comment]
Ну тогда редактирование текстов -- подмножество редактирования узлов

**Comment by Nastuya** [comment]
Короче, надо запилить, чтобы можно было в любой момент убирать\вставлять узел, а не только текст редактировать
