### ISSUE TITLE
Мокапы

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#27]
Три страницы:
1) лэндинг
2) мейкер
3) вьювер

**Comment by leshakoss** [comment]
![1](https://cloud.githubusercontent.com/assets/566319/6727726/0f1b8db6-ce46-11e4-8a06-e987db4d1785.PNG)
![2](https://cloud.githubusercontent.com/assets/566319/6727727/0f520274-ce46-11e4-9431-6f6509f74316.PNG)
CC0

**Comment by 102** [comment]
![mockup](https://cloud.githubusercontent.com/assets/5839225/6730871/7772b816-ce6a-11e4-9b40-9456169d5733.png)
Viewer вижу как-то так (надо добавить будет к квестам общее описание и общую картинку). Ну и после авторизации прикрутить какой-нибудь рейтинг (хотя бы по количеству фэйворитс будет нормально)

**Comment by leshakoss** [comment]
@grdesu 
![commit](https://cloud.githubusercontent.com/assets/566319/7336279/ca9ebc76-ec0e-11e4-9f76-46109b086ac2.jpg)
