### ISSUE TITLE
Если квестов много — плохо

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#38]
![screen shot 2015-03-29 at 14 27 42](https://cloud.githubusercontent.com/assets/566319/6884702/800c7278-d617-11e4-8bc7-57119f2f1f34.png)
Все не вмещаются.
В мейкере нужно починить выпадающий список
Во вьювере добавить паджинейшн

**Comment by 102** [comment]
Это, кстати, повторение #35;
Другое дело, что в ab9c32367e7a18b46ac5829c984977019bd21277 я опечатался, лол
