### ISSUE TITLE
Невозможно создать новые узлы в мейкере

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#47]
![screen shot 2015-04-26 at 12 50 22](https://cloud.githubusercontent.com/assets/566319/7336218/a16272d4-ec0a-11e4-86c6-911f59d5ae5f.png)
Нет кнопки (((((((((((((((

**Comment by 102** [comment]
Всего-навсего надо выбрать квест (ну или написать что-нибудь в одно из полей сверху). Ну или создавать объект $scope._q заранее
