### ISSUE TITLE
Сделать нормальную структуру приложения

### ISSUE THREAD

**Issue by leshakoss** [spb201/visual-novel#64]
См. https://github.com/spb201/spb201.github.io/wiki/Спецификация-Milestone-5

**Comment by 102** [comment]
da ty ohuel

**Comment by leshakoss** [comment]
@grdesu я базарю. Ландинг нахуй не нужен

**Comment by 102** [comment]
@LeshaKoss нахуй я его верстал тогда?

**Comment by 102** [comment]
@LeshaKoss ((((((((((((((((((((((((((((((((((((((((((((((((((((((

**Comment by leshakoss** [comment]
@102 я подключил библиотеку для роутинга 5f6154e533e
теперь твоя задача засунуть public novels на #/, my novels на #/mynovels, мейкер на #/edit и ландинг в #about
ну и ксс почини

**Comment by 102** [comment]
96e4a9eaad380522a44f0708373ce546cb1a56ed
9d53515e634f47c5befc361f0d82dc6a5cd542ea
etc
