### ISSUE TITLE
Добавить подсказки для кнопок управления в mynovels

### ISSUE THREAD

**Issue by 102** [spb201/visual-novel#92]
Опубликовать/разопубликовать совсем не очевидны, если не читать перед использованием спецификацию

**Comment by leshakoss** [comment]
Я считаю что вместо иконки нужно так и написать: "Опубликовать".
Что то вроде (Publish) (:memo:) (:heavy_multiplication_x:)
Я этого не сделал потому что если вместо иконки добавить текст, то кнопка станет овальной, а не сосискообразной (что было бы красивее)

**Comment by leshakoss** [comment]
Или даже подписать их все и разместить вертикально (заалайнив к правому краю)
(Publish :arrow_up:)
(Edit :memo:)
(Delete :heavy_multiplication_x:)

**Comment by 102** [comment]
Ну они явно должны быть сделаны в одном стиле, так что первый варант как-то не очень.
Можно сделать все таки по ховеру текст (так и было задумано в начале же, вроде бы)
